### ISSUE TITLE
Feature request: option to flash green/red bar on success/failure of tests

### ISSUE THREAD

**Issue by Alok** [janko-m/vim-test#163] opened 2016-12-25 01:49 UTC
Basically the color feedback from [pytest.vim](https://github.com/alfredodeza/pytest.vim)

**Comment by janko-m** [comment] 2016-12-25 05:39
This seems to be a duplicate of https://github.com/janko-m/vim-test/issues/150, so let's move the discussion there.

**Closed by janko-m** 2016-12-25 05:39 UTC
