### ISSUE TITLE
dispatch strategy behaves different than Dispatch itself

### ISSUE THREAD

**Issue by chrkau** [janko-m/vim-test#73] opened 2015-11-03 10:10 UTC
When using Dispatch the opened split/window closes once the given tests ran without errors. Dispatch also opens a quickfix split if the test suite threw any errors. The dispatch strategy does neither of those things.

Is this intended and if yes how can I imitate that behavior in vim-test?

Thanks.

**Comment by janko-m** [comment] 2015-11-03 11:03
That's strange, the dispatch strategy calls `:Dispatch <cmd>` directly (as you can see [here](https://github.com/janko-m/vim-test/blob/master/autoload/test/strategy.vim#L26)), so it should behave exactly like calling it directly.

What is the behaviour you're getting? Is there some indication that the command has been run at all? Also, are you by any chance using MacVim or GVim? Because in that case a split is open in the Terminal directly and you won't be able to see it, although the quickfix is still opened.

**Comment by chrkau** [comment] 2015-11-03 12:24
After testing again I realized I actually do get a quickfix split. But it opens regardless of if there were any failing tests or not.

I have no idea about Vimscript but I always thought Dispatch checks the exit code of the rspec/test command and decides of opens the quickfix window. Could this be the problem here?

**Comment by janko-m** [comment] 2015-11-03 12:26
Yeah, I think it does do that. When you run your test command with `:Dispatch` directly, does it behave differently than when you run it through vim-test?

**Comment by chrkau** [comment] 2015-11-03 12:30
Yes: :Dispatch opens a tmux split, runs the given tests and closes the tmux split without opening the quickfix window.

:TestFile opens a tmux split, runs the given tests, closes the tmux split and opens a quickfix window containing the complete test suite output.

**Comment by janko-m** [comment] 2015-11-03 12:33
When you run `:TestFile`, try running `:echo g:test#last_command`, and see if it matches the command that you ran when using `:Dispatch` directly, otherwise try running `:Dispatch` with that command and see if you still get different behaviour.

**Comment by chrkau** [comment] 2015-11-03 12:47
`:echo g:test#last_command` returns `zeus rspec spec/controllers/ticketings_controller_spec.rb`. Running `:Dispatch zeus rspec spec/controllers/ticketings_controller_spec.rb` behaves exactly like `:TestFile` (opens quickfix).

I Dispatch seems to run `!zeus rspec spec/controllers/ticketings_controller_spec.rb`, too. It doesn't open a quickfix though.

**Comment by janko-m** [comment] 2015-11-03 12:55
This should probably then be fixed in vim-dispatch, because it should detect that it's running `rspec` from the command string. Or you just need to debug by looking at exit statuses, although it probably isn't related to that. I don't know why it has this behaviour, but it definitely isn't a bug in vim-test.

**Closed by janko-m** 2015-11-03 12:55 UTC

**Comment by dlm** [comment] 2016-02-19 15:26
Maybe I'm a little late to the discussion, but @chrkau and @janko-m, I hit the same thing.  I think the problem is with @charkau's vim-dispatch configuration.  @chrkau, have you tried adding to your vimrc:
```
let g:dispatch_compilers = {'zeus': ''}
```

For more on dispatch_compilers see:
https://github.com/tpope/vim-dispatch/blob/master/doc/dispatch.txt#L53-L61
