### ISSUE TITLE
Tests run, but immediately switch back to vim

### ISSUE THREAD

**Issue by timpwbaker** [janko-m/vim-test#315] opened 2018-08-23 08:06 UTC
Hi, thanks for the great package!

I am using vim-test to run go and ruby tests using the basic strategy, the tests run fine, but as soon as they are complete, pass or failure, the terminal switches back to vim, so I have to exit vim to see the results. I have previously used https://github.com/thoughtbot/vim-rspec which does not have this issue.

The terminal outputs the `Press ENTER or type command to continue` as normal after running the tests, but does not wait for me to press enter.

I have read through much of the package and can't for the life of me find why it's doing this. Any help would be appreciated.

![tests](https://user-images.githubusercontent.com/8363245/44512779-837a7e80-a6b3-11e8-8581-d6888acb7c58.gif)

**Comment by janko-m** [comment] 2018-08-23 13:08
That's weird, for me it works normally. Test.vim just runs the command via `:!<cmd>`, which should wait for the keypress after finish. I don't know what could cause the behaviour you're describing.

**Comment by timpwbaker** [comment] 2018-08-23 13:16
No worries. Thanks. I'll post it here if I work it out.

**Comment by janko-m** [comment] 2018-09-23 20:28
I will close this, as there doesn't seem like there is anything that can be done on the vim-test side.

**Closed by janko-m** 2018-09-23 20:28 UTC

**Comment by timpwbaker** [comment] 2018-09-24 14:47
Sorry, I forgot to close it @janko-m - I found the typo in my vimrc in the end.

**Comment by chrisfrank** [comment] 2018-11-01 16:55
@timpwbaker I'm having the same issue on a Mac. Do you remember what the typo in your vimrc was? Thanks!

**Comment by timpwbaker** [comment] 2018-11-01 17:09
Yeah, trailing character in my command. Paste the relavent lines from your
vimrc?

**Comment by chrisfrank** [comment] 2018-11-01 17:46
That did it! Thank so you much. I went from what I pasted from the README, which switched back to vim immediately...
```
nmap <silent> t<C-n> :TestNearest<CR> " t Ctrl+n
nmap <silent> t<C-f> :TestFile<CR>    " t Ctrl+f
nmap <silent> t<C-s> :TestSuite<CR>   " t Ctrl+s
nmap <silent> t<C-l> :TestLast<CR>    " t Ctrl+l
nmap <silent> t<C-g> :TestVisit<CR>   " t Ctrl+g
```

... to this, which works as intended:
```
nmap <silent> t<C-n> :TestNearest<CR>
nmap <silent> t<C-f> :TestFile<CR>
nmap <silent> t<C-s> :TestSuite<CR>
nmap <silent> t<C-l> :TestLast<CR>
nmap <silent> t<C-g> :TestVisit<CR>
```

Thanks again @timpwbaker for your help, and thanks @janko-m for this great plugin, and for your wonderful contributions to the Ruby community.

**Comment by janko-m** [comment] 2018-11-01 18:22
@chrisfrank You're welcome! ❤️ 

I've updated the README to remove those comments (I didn't know they actually changed behaviour 😅).
