### ISSUE TITLE
Rails minitest starting time is too long

### ISSUE THREAD

**Issue by xfyuan** [janko-m/vim-test#260] opened 2017-12-26 01:34 UTC
After I pull the last commit 5ed9e7b85ac5357ac1b717bacc79b253ce8241d8, the rails minitest starting time is too long(test running screen shows after about 10~15s). But when I switch to the previous commit 5bed82cfdd0fbc1eaca77114aa4e9e95c1274416, the starting time is as regular quickly as normal.

So can double check it?

**Comment by janko-m** [comment] 2017-12-27 09:09
@xfyuan Could you create an example Rails application which exhibits this slow behaviour? I cannot imagine why this change would slow things down 🤔

**Comment by janko-m** [comment] 2018-01-10 09:33
My guess is that `glob(**/*.rake)` has to search too many files in your project. Could you check whether all temporary files like `tmp/` directory are in your vim's `wildignore` list?

**Comment by goozler** [comment] 2018-01-30 12:06
Hi! 

I have the same issue and it prevents me to use the newest version of your great plugin :-(

I can't say that my project is huge and I can't share it. I tried to find some kind of an example project with minitest and check how it's going there but haven't found anything useful. 

`:set wildignore` in my vim returns this 
```
wildignore=*/tmp/*,*.so,*.swp,*.zip,*/build/*,*/node_modules/*,*/bower_components/*,*/test/files/*,*/features/vcr/*,*.cache
```

Could you help me figure out what slows down the plugin?

**Comment by janko-m** [comment] 2018-01-30 12:20
@goozler When you execute the following VimL snippet from the directory of your Rails application, is it slow?

```vim
let rake_content = []
for rake_file in glob('Rakefile', 0, 1) + glob('**/*.rake', 0, 1)
  let rake_content += readfile(rake_file)
endfor

call match(rake_content, 'Rake::TestTask')
```

If yes, could you try to determine whether it's the `for` loop or the `match`?

**Comment by goozler** [comment] 2018-01-30 13:03
Yes, the problem is in the loop. It takes about 3 seconds. I don't know how to display all the scanned files, though. 

In general, personally, I'm fine to set up the command by local vimrc file or something like for the project. Processing even few files on every command execution look like a little overhead for me. Is it possible to cache the result for running vim instance or something like that?

**Comment by goozler** [comment] 2018-01-30 14:00
I have 13 `*.rake` files in the project directory and ~54k files in general. Most of them in `tmp`, `node_modules` and so on, probably, my `wildignore` is incorrect or just aren't taken into account.

Another issue with that my vim is hanging during running that researching.

I think I missed the original source of the issue and I want to say thank you for looking at this now. I don't know the solution to both issues. Maybe it's ok to make this optional like just give an ability to choose if a user would like to investigate the files or use the previous basic solution. Does it make sense?

**Comment by semanticart** [comment] 2018-02-26 03:53
I'm hitting a similar issue with the for loop. I have confirmed that my wildignore is working properly but even excluding .git, tmp, log, etc, I still have a decent number of files and nested directories (though not an insane number as `git ls-files | wc -l` reports ~5k).

It appears that a single run of `TestFile` causes `test#ruby#minitest#executable()` to be invoked four times. Perhaps there's some memoization that can be done to help out here?

I modified `test#ruby#minitest#executable()` to debug like so

```vim
  echom expand("<sfile>")

  let start_time = reltime()
  let rake_content = []
  for rake_file in glob('Rakefile', 0, 1) + glob('**/*.rake', 0, 1)
    let rake_content += readfile(rake_file)
  endfor
  echom "elapsed time:" reltimestr(reltime(start_time))
```

Note that only the `echom` and `let start_time = reltime()` lines are new. Here was the output:

```
function test#run[5]..test#test_file[1]..test#determine_runner[4]..test#base#test_file[1]..test#ruby#m#test_file[1]..test#base#executable[4]..test#ruby#minitest#executable
elapsed time:   0.284515
function test#run[16]..test#determine_runner[4]..test#base#test_file[1]..test#ruby#m#test_file[1]..test#base#executable[4]..test#ruby#minitest#executable
elapsed time:   0.274968
function test#run[26]..test#execute[17]..test#base#executable[4]..test#ruby#minitest#executable
elapsed time:   0.278261
function test#run[26]..test#execute[18]..test#base#build_args[1]..test#ruby#minitest#build_args[21]..test#base#executable[4]..test#ruby#minitest#executable
elapsed time:   0.280566
```

---

Incidentally, I measured `call match(rake_content, 'Rake::TestTask')` in my project and `0.000268` was a typical timing.

---

Thankfully, you've designed the plugin such that workarounds are easy. I'm using the following in the meantime to skip this function altogether:

```vim
let g:test#ruby#minitest#executable = './bin/rake test'
```

**Comment by semanticart** [comment] 2018-03-05 00:39
@janko-m nice work! My naive testing shows it is faster by a little more than 2x.

```
function test#run[5]..test#test_file[1]..test#determine_runner[4]..test#base#test_file[1]..test#ruby#m#test_file[1]..test#base#executable[4]..test#ruby#minitest#executable
elapsed time:   0.116451
function test#run[16]..test#determine_runner[4]..test#base#test_file[1]..test#ruby#m#test_file[1]..test#base#executable[4]..test#ruby#minitest#executable
elapsed time:   0.110669
function test#run[26]..test#execute[17]..test#base#executable[4]..test#ruby#minitest#executable
elapsed time:   0.113994
function test#run[26]..test#execute[18]..test#base#build_args[1]..test#ruby#minitest#build_args[21]..test#base#executable[4]..test#ruby#minitest#executable
elapsed time:   0.117274
```

That said, the delay is still noticeable enough that I'm going to stick with manually setting the executable.

And FWIW, I'm fine with that solution. The library putting in a strong effort to find the right executable if one isn't provided makes sense. It just happened to be fast enough before this issue that I never bothered to provide the executable directly.

**Comment by janko-m** [comment] 2018-03-05 11:29
@semanticart Thanks so much for testing this out!

Ok, I reverted back to the original behaviour (no searching for `*.rake` files at all), because the speed of running tests is really important to me. I think it's better that people add a workaround such as [this](https://github.com/janko-m/vim-test/issues/257#issuecomment-352045593) to make the runner be detected in these rare cases.

Hopefully the speed should be good again, so I'll close this one.

**Closed by janko-m** 2018-03-05 11:29 UTC
Labels: needs info
