### ISSUE TITLE
Panel sizes are not restored when terminal is closed.

### ISSUE THREAD

**Issue by PhML** [janko-m/vim-test#122] opened 2016-06-10 13:13 UTC
When I close the terminal after running vim-test, panels are horizontally equalized.
This is annoying when you have set the size manually.

The horizontal size should be stored before opening the terminal and restored after its close.

**Comment by janko-m** [comment] 2016-06-10 13:44
Ah, I've noticed that some time before, but completely forgot about it. This seems to be the product of `botright new` command, after you close the opened window things don't go back to normal. An alternative is to use `belowright new` (or probably just `new`), which has behaviour that it opens a terminal right below the current buffer, with the same width as the current buffer (as opposed to `botright` which opens the window on the bottom in full-width).

Can you try typing in the following and let me know if this is what you want:

```vim
:belowright new | call termopen('your test command') | startinsert
```

I think that's a better default behaviour, since it seems to bring windows back to original.

**Comment by PhML** [comment] 2016-06-13 08:30
Indeed, it brings windows back to original.
I liked `botright` too, is it possible to add an option to configure which behaviour to use ?

But most important: is it a bug from vim that should be reported upstream?

**Comment by janko-m** [comment] 2016-06-13 09:34
I believe so. So, the issue is that when you close a window opened with `botright`, all windows that are in vertical line of where your cursor is currently will properly get resized back, while other windows won't. So if you're inside the terminal window opened by `botright`, Vim considers that you're in the "left lane", and after closing it you will be put on the nearest left-most buffer (Test.vim overrides that to put you back in the alternate buffer instead).

It's strange that I couldn't find people complaining about this behaviour on the Internet. I expected that I will find people having problem with it on [Neoterm](https://github.com/kassio/neoterm), but no luck.

However, I realized that [FZF](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim) is doing the same thing, opening the Neovim terminal on the very bottom full-width, and closing the terminal keeps the windows intact. The difference that I noticed is that when FZF opens the Terminal window, no other windows move.

While writing this I figured that if you give `botright` an explicit window height, e.g. `:botright20 new`, it will have the desired behaviour. Now I just need to figure out what should be the default value. The author of FZF managed to have it as a [percentage](https://github.com/junegunn/fzf/blob/c39c039e155c50bcf8fecc5956c4bdd3b5c6bea1/plugin/fzf.vim#L24), and he did some calculations.

Btw, have you tried out [Neoterm](https://github.com/kassio/neoterm) with Test.vim (by setting `let test#strategy = 'neoterm'`)? It is very configurable, and among other things lets you set this buffer height, which then has desired behaviour (Neoterm also uses `botright`). In https://github.com/janko-m/vim-test/issues/121 I basically discuss whether the `neovim` strategy should be deprecated over Neoterm, because I don't want to start introducing strategy-specific configuration in Test.vim.

**Comment by janko-m** [comment] 2016-06-17 16:38
After testing FZF again, I managed to reproduce the same resizing bug, `botright<n>` still messes up window placement, so this behaviour is definitely is something that should be reported to the Vim project.
I don't know what should now be the course of action for test.vim, though.

**Comment by janko-m** [comment] 2016-11-28 04:44
Closing as a duplicate of https://github.com/janko-m/vim-test/issues/146.

**Closed** 2016-11-28 04:44 UTC
