### ISSUE TITLE
Error when running vim-flavor

### ISSUE THREAD

**Issue by codeinabox** [janko-m/vim-test#263] opened 2018-01-11 16:13 UTC
I am trying to run the tests locally but I get the following error:-

> gem install vim-flavor
> Successfully installed vim-flavor-2.2.1
> Parsing documentation for vim-flavor-2.2.1
> Done installing documentation for vim-flavor after 0 seconds
> 1 gem installed
> 
> vim-flavor test spec/
> -------- Preparing dependencies
> Checking versions...
>   Use junegunn/vader.vim ... 0.3.0
>   Use kana/vim-vspec ... 1.6.1
>   Use tpope/vim-fireplace ... v1.1
> Deploying plugins...
>   junegunn/vader.vim 0.3.0 ... skipped (already deployed)
>   kana/vim-vspec 1.6.1 ... skipped (already deployed)
>   tpope/vim-fireplace v1.1 ... skipped (already deployed)
> Completed.
> -------- Testing a Vim plugin
> spec/ava_spec.vim ............
>
> ~/workspace/vim-test/spec/support/helpers.vim, line 7
> Vim(function):E746: Function name does not match script file name: test#strategy#basic
> Bailout called.  Further testing stopped:  Unexpected error happened while processing a test script.
> FAILED--Further testing stopped: Unexpected error happened while processing a test script.

**Comment by janko-m** [comment] 2018-01-11 16:16
@codeinabox Which versions of Ruby, vim-flavor and Vim are you using?

**Comment by codeinabox** [comment] 2018-01-11 16:19
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
vim-flavor 2.2.1
I have NVIM v0.2.2 aliased to `vi` and Vi IMproved 8.0.1400 aliases to `vim`

**Comment by janko-m** [comment] 2018-01-13 15:57
@codeinabox I couldn't reproduce this, I've made the exact same setup as you have. I think we might have slightly different Vim versions, because the error that occurred is a Vim error. This is my version (installed with Homebrew):

<details>
<summary>vim --version</summary>

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 19:10:24)
Included patches: 1-503, 505-642
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    -mouse_sgr       +tag_old_static
-arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           -mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     -termguicolors
-browse          -footer          +multi_byte      +terminfo
+builtin_terms   +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
-clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        -perl            +vertsplit
+cmdline_hist    -keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        -langmap         +printer         +visualextra
-conceal         +libcall         -profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             -rightleft       +writebackup
+diff            +menu            +ruby/dyn        -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
-emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            -mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
-farsi           -mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa
```
</details>

**Comment by codeinabox** [comment] 2018-01-18 11:16
Hmmm, short of rebuilding my development environment I wonder how I can get the tests working for me again.

**Comment by janko-m** [comment] 2018-01-18 11:35
@codeinabox Actually, I'm running a different Vim version – `8.0.642`. Can you try upgrading your Vim to that version or higher?

**Comment by janko-m** [comment] 2018-01-18 11:37
To clarify, that's what I see when I call the `:version` Vim command.

**Comment by codeinabox** [comment] 2018-01-18 12:22
I do have the latest version installed though as I update Homebrew very regularly

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  6 2018 15:48:06)
macOS version
Included patches: 1-1400
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python            +vreplace
+conceal           +linebreak         -python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               +ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.13 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.1/lib/perl5/5.26.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.5.0 -lobjc
```

**Comment by voronkovich** [comment] 2018-01-27 20:08
@janko-m, @codeinabox The problem was introduced by this patch: https://github.com/vim/vim/commit/a9b579f3d7463720a316e11e77a7a9fbb9267986

Try to run this command:
```
:echo has("patch-7.4.2058")
```

**Comment by codeinabox** [comment] 2018-01-29 11:47
@voronkovich well spotted, both my Vim and Neovim have that patch. Is there a fix or workaround for this issue?

**Comment by janko-m** [comment] 2018-01-29 11:55
I also have the patch, but I'm not exhibiting the same error.

@codeinabox Yes, @voronkovich has opened https://github.com/janko-m/vim-test/pull/267 as the workaround, could you run tests on that branch and see if the error goes away?

**Comment by janko-m** [comment] 2018-01-29 18:10
Fixed in https://github.com/janko-m/vim-test/pull/267.

**Closed by janko-m** 2018-01-29 18:10 UTC
Labels: bug
