### ISSUE TITLE
cursor always go back to first panel after test run which is very annoying

### ISSUE THREAD

**Issue by Orgil** [janko-m/vim-test#98] opened 2016-04-05 12:00 UTC
If i have opened nerdtree along with current buffer, cursor goes to nerdtree buffer after test window closed. So i have to switch panel everytime, which is very annoying.

I'm using neovim in iterm2 terminal using neovim strategy.

**Comment by janko-m** [comment] 2016-04-08 11:33
Hmm, that's unfortunate. I think this is because the NERD Tree buffer is somehow set up to be the "main" buffer where Vim returns to when a buffer is closed. If you replace the NERD Tree buffer with a regular buffer, does the same thing happen?

Unfortunately, I don't think I can help here, as I don't think it's possible to control where the cursor will go after the terminal window is closed. And I don't want to make some specific workarounds for NERD Tree. One option is to figure out whether the bug is in Neovim or NERD Tree, and file an issue there. Another option is to switch to [vinegar.vim](https://github.com/tpope/vim-vinegar), which I use as it is so much better than NERD Tree; it's just a wrapper around Vim's built in netrw file explorer, with some really convenient mappings.

**Comment by Soliah** [comment] 2016-04-13 12:26
This occurs because of neovim's built in terminal support and I've run into the same issue. I note that this doesn't occur with other plugins that have neovim support like https://github.com/junegunn/fzf.vim. Having 2 splits open, it always returns focus back to the original split whereas with vim-test and the neovim strategy it always goes back to the first split.

Will try fzf.vim and how it figures out how to go back to the original split.

**Comment by Soliah** [comment] 2016-04-13 12:50
Looks like the magic starts here but I'm not familiar with vimscript enough yet to figure out what's going on: https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L323

**Comment by janko-m** [comment] 2016-04-13 13:10
Fzf uses Neovim's terminal when on Neovim? If yes, does it indeed work with NERD Tree? Because for regular splits the vim-test's neovim strategy also works.

The problem is that, what the neovim strategy does is that it executes a command inside a terminal and brings you to "insert mode" inside that terminal, which allows you to "Press ENTER or type command to continue" (which is what the prompt says). So, after bringing you to insert mode the strategy stops having control. That means that the strategy would have to detect that you've closed the terminal, and bring you back to the window you were at before. And I'm not sure if this can be done for that specific window vim-test opened, because I think if vim-test does it globally on any opened terminal window it could mess something up.

**Comment by Soliah** [comment] 2016-04-13 13:34
I haven't tested with nerd tree but from my use wherever I activate fzf in neovim, after dismissing the fzf terminal window, focus is always returned to the original window I was in.

Maybe @junegunn could shed some more light on how fzf.vim behaves this way as its a bit beyond me.

**Comment by janko-m** [comment] 2016-04-13 13:43
Aha, I see now, so test.vim doesn't work with you for normal steps. I was able to reproduce this by making a vertical split, and then going to the **right window** and calling and closing Neovim's terminal, which makes the cursor go back to the **left window** instead of the right one. Ok, I will go read fzf.vim's source code, thanks for the pointers where to look.

**Comment by dalizard** [comment] 2016-05-26 08:23
@janko-m Are you in a need for any help here? :) This feature would be lovely!

**Comment by janko-m** [comment] 2016-05-27 03:09
@dalizard If you have some spare time and could investigate this (e.g. take a look at fzf.vim linked above), that would be really helpful.

**Comment by janko-m** [comment] 2016-05-27 03:16
It looks like @KevinSjoberg made some improved Neovim strategy (https://github.com/KevinSjoberg/vim-test-neovim-error-only), maybe it fixes the problem, and could be made default in vim-test.

**Comment by dalizard** [comment] 2016-05-27 13:46
@janko-m I've been playing around with it and it works very well. Great work, @@KevinSjoberg!

**Closed** 2016-06-01 18:48 UTC
