### ISSUE TITLE
jasmine-node support

### ISSUE THREAD

**Issue by austincrft** [janko-m/vim-test#157] opened 2016-12-04 22:16 UTC
Are you open to supporting [jasmine-node](https://github.com/mhevery/jasmine-node)?

I don't mind doing the work, just want to make sure it's inline with the goals of this project.

**Comment by janko-m** [comment] 2016-12-05 02:07
The `jasmine` test runner previously used jasmine-node, but in https://github.com/janko-m/vim-test/commit/6049bcf88ef9eaa503c8ed04ddd21dac05c0712a I changed it to use jasmine-npm, because

> Jasmine-npm is created and maintained by the Jasmine authors, and
> jasmine-node was created by the community and isn't being maintained
> anymore. The biggest advantage of jasmine-npm is the support for
> filtering tests, which test.vim can then use for running nearest tests.

I'm not sure if you were aware of jasmine-npm; in that case, are there any advantages of jasmine-node?

**Comment by austincrft** [comment] 2016-12-07 18:49
Ah, I didn't understand that the two were compatible. I am still having trouble running the tests, though. When I open a `*.spec.js` file and run `:TestFile` I get an error saying `Not a test file`.

**Comment by janko-m** [comment] 2016-12-08 15:51
@austincrft This is the regex used for checking whether something is a Jasmine test file:

```
\v^spec/.*spec\.(js|jsx|coffee)$
```

Can you see why the file doesn't match the regex? Are your tests located in the `spec/` folder?

**Comment by austincrft** [comment] 2016-12-08 20:24
Ah, it looks like that was the problem. I'm working through some of the JavaScript problems on [exercism.io](http://exercism.io/), and they suggest using `jasmine-node` and calling the `*.spec.js` file as an argument. I can do the same with jasmine-npm using `jasmine *.spec.js`, but the plugin doesn't recognize it because it isn't in a `spec/` directory.

This is my first time using Jasmine, so I'm not sure about the best practices. Would you suggest that I start a conversation over there about adhering more properly to the Jasmine best practices?

**Comment by austincrft** [comment] 2016-12-08 20:28
Although I did notice that in the `spec/support/jasmine.json` file, you can name the directory differently using the `spec_dir` field:
``` json
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
```

If someone were to use a differently named spec directory, this plugin wouldn't support it.

**Comment by janko-m** [comment] 2016-12-09 00:26
@austincrft The problem is there isn't really a way to distinguish between Jasmine, Karma and Mocha test files – they can all end in `spec.js` and their syntax is exactly the same. I think test.vim will have to start requiring the presence of runner-specific configuration files to be present:

* `**/jasmine.json` for Jasmine
* `karma.conf.js` or `config/karma.conf.js` for Karma
* `test/mocha.opts` for Mocha

I also want to introduce some general "verbose" mode of test.vim, which will output how exactly test.vim determined the test runner, so that people know why some test runner was chosen over the other.

**Comment by austincrft** [comment] 2016-12-09 18:21
Both of those sound like good ideas to me, assuming that you could run the `:Jasmine` command on a specific file if a runner isn't found.

Speaking of which, I do not see a `:Jasmine` command, even though I can run `:TestSuite` and get results. I assumed that the `:Jasmine` command would just run the CLI `jasmine` command with the provided args. So `:Jasmine %` would run `jasmine` on the current file.

Why would I not be able to see the `:Jasmine` command? Are my assumptions correct?

**Comment by janko-m** [comment] 2016-12-09 18:30
@austincrft The runner commands are disabled by default, so that they don't pollute the Vim command namespace. You need to explicitly enable the ones that you want to use in your `.vimrc`:

```
let g:test#runner_commands = ['Jasmine']
```

**Comment by codeinabox** [comment] 2017-04-11 17:32
Closing but please reopen if you need help creating a PR

**Closed by codeinabox** 2017-04-11 17:32 UTC
