### ISSUE TITLE
Version 1.3.0 breaks python runner config

### ISSUE THREAD

**Issue by dustinfarris** [janko-m/vim-test#55] opened 2015-09-03 19:10 UTC
Upgrading to v1.3.0 seems to have broken the runner config.  I have mine set to pytest, but it keeps trying to use nose.

**Comment by janko-m** [comment] 2015-09-03 19:57
Nose is being used even after you `let g:test#python#runner = "pytest"`?

**Comment by dustinfarris** [comment] 2015-09-03 20:09
Yes

**Comment by dustinfarris** [comment] 2015-09-03 20:09
I reverted back to v1.2.0 and the problem went away.

**Comment by janko-m** [comment] 2015-09-03 20:21
I'm really baffled by what could it be. I did loosen up Nose's file pattern, but PyTest is checked before Nose, so that shouldn't matter. When you're in a test file, can you try

```vim
:echo test#python#pytest#test_file(expand('%'))
:echo fnamemodify(expand('%'), ':t') =~# g:test#python#pytest#file_pattern
```

What does each one return?

**Comment by dustinfarris** [comment] 2015-09-03 21:02
When using v1.3.0:

```
:echo test#python#pytest#test_file(expand('%'))
1
```

```
:echo fnamemodify(expand('%'), ':t') =~# g:test#python#pytest#file_pattern
1
```

When using v1.2.0:

```
:echo test#python#pytest#test_file(expand('%'))
1
```

```
:echo fnamemodify(expand('%'), ':t') =~# g:test#python#pytest#file_pattern
E121: Undefined variable: g:test#python#pytest#file_pattern
```

**Comment by janko-m** [comment] 2015-09-03 21:12
Hmm, then it should work. I cannot reproduce the issue. I don't have my Python runner set explicity, and it still defaults to PyTest. I tried to reproduce in the following way:

```
$ touch test_foo.py
$ vim test_foo.py
:TestFile
```
```
py.test test_foo.py
```

What do you get when you try to execute the above? I'm trying to figure what are the differences between our setups.

**Comment by janko-m** [comment] 2015-09-13 09:18
@dustinfarris Could you help me more on this? :)

**Comment by janko-m** [comment] 2015-09-15 19:34
I will close this for now, please reopen if the issue persists and you can give me a reproducable project structure and vim-test configuration.

**Closed by janko-m** 2015-09-15 19:34 UTC
